### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 6DiegoDiego9** [idosal/assistant-chat-gpt#10]
I tried it today with Chrome (last version) / Windows 11 and it stays forever on blinking "ChassistantGPT is ready for your voice commands".
Ctrl+shift+E does nothing.
Does it still work to you?

**Comment by idosal** [comment]
"Ready for voice conmands" signals that you gave ChassistantGPT microphone permissions, so it's listening for the voice trigger (and the prompt itself). It should always be blinking.
Ctrl+shift+E should trigger the prompt. Does the voice trigger (e.g., "Hey girl") work for you?
It definitely works on Mac. I'll test it on my Windows tomorrow.

**Comment by 6DiegoDiego9** [comment]
"Hey girl" does nothing, nor does any other custom words I tried

**Comment by idosal** [comment]
Works for me. Does restarting Chrome help? What other extensions do you have installed?
If that doesn't work, could you please try a manual installation?

**Comment by 6DiegoDiego9** [comment]
Solved!
It turned out that the cause was external to your app: my LG Gram notebook has a preinstalled "protection" software that silently mutes mic and webcam until turned "off".
