### ISSUE TITLE
saying need to be authenticate 

### ISSUE THREAD

**Issue by Samratthebest** [idosal/assistant-chat-gpt#11]
its saying i have to authenticate it but not showing any way to use this

**Comment by Samratthebest** [comment]
i am using in ms edge

**Comment by idosal** [comment]
You need to authenticate with ChatGPT every once in a while as they expire sessions (although the extension does refresh it in the background so long as you have an internet connection). The popup shows the URL - https://chat.openai.com/chat.
Note that Edge isn't officially supported (I haven't tested it there). Please let me know if it works for you (and what doesn't) so I can add it.
