### ISSUE TITLE
Doesn't work with Vivaldi

### ISSUE THREAD

**Issue by heldheld** [idosal/assistant-chat-gpt#12]
I use Vivaldi, a Chromium browser on which I have never had any issues with Chrome Extensions not working until now. Seems that ChassistantGPT doesn't like other Chromium browsers. Any way of fixing this?

**Comment by idosal** [comment]
Indeed, it only works with Chrome and Edge. The reason is that the text-to-speech engine is only free in those browsers. Other than that, it is technically possible to enable it in other browsers.
