### ISSUE TITLE
Change Wake Word

### ISSUE THREAD

**Issue by neoOpus** [idosal/assistant-chat-gpt#4]
Please make it possible to change wake word from "Hey Girl" to anything else and also make it possible to not send that to ChatGPT as sometimes it gets said twice and this confuse it... I think this can be simply implanted by adding a filtre of the prompt...

**Comment by idosal** [comment]
Interesting. In what scenario is it said twice?
It's pretty easy to make the prompt configurable. I hope I'll get to it soon (probably after language support). Contributions are welcome. :)

**Comment by neoOpus** [comment]
Simply when you say Hey Girl but don't hear anything so you repeat that but the latency catch up and it write that part of the prompt... so it would be better to add a filter and also wait before sending the prompt or wait for another keyword like (Answer) and it would be great to be able to skip or mute the TTS when it is irrelevant...

**Comment by idosal** [comment]
Done.

**Comment by neoOpus** [comment]
The custom wake word doesn't work, I change it and it does nothing... and it is not possible to save any of the setting in MS edge (I didn't try in other browsers yet but I am trying in Google Chrome in ChromeOS right now)

It would be great to have the voice selection saved and have them sorted by language, I will try to help with the code myself but I am not a coder (just a tinkerer) but maybe with the help of ChatGPT I can implant some of the features :)

**Comment by idosal** [comment]
It definitely works on Chrome (MacOS), which is currently the only officially supported browser. I've tested it in multiple languages. Please make sure there is no significant noise that may confuse the TTS engine. If all fails, you may use the new push-to-talk feature by pressing Ctrl+Shift+E.

Regarding persistence - it's easy to implement by saving the settings to chrome.storage.sync, but I doubt I'll get to it in the next few days.

Thanks for the feedback. :)

**Comment by neoOpus** [comment]
OK Thanks, I will take time to study the source code and see what I can do myself... I wish that more coders join this project since ChatGPT is very trendy at this moment and there are many who are launching similar things instead of working on project like this...

I have several basic suggestions to improve this so I will open issues with them if you don't mind so that you can add them to the todolist and maybe some other will contribute by implanting some of them.

**Comment by idosal** [comment]
Sounds good to me. I'd love to see contributions to the project.
