### ISSUE TITLE
Triggering via key press as an option.

### ISSUE THREAD

**Issue by vojin7** [idosal/assistant-chat-gpt#5]
Awesome job, best implentation yet! 

The "hey smth" routine is really getting old - not your fault, of course. :)

How about pressing space to talk, like in Zoom? Perhaps, only when the options screen is in focus?

Super simple, large target key impossible to miss, smoother expererence for the family members we're trying to impress. 

Thanks.

**Comment by idosal** [comment]
Thanks, I'm glad you find it useful!
It's a good idea. How about a key bind, something like Cmd/Ctrl + Shift from anywhere in the browser?

**Comment by vojin7** [comment]
Even better!

**Comment by idosal** [comment]
Cool. It's a simple addition. If no one else takes it, I'll try to do it tomorrow.

**Comment by vojin7** [comment]
Thanks, you're awesome. Have a great day!

**Comment by idosal** [comment]
Thanks, you too. Just to clarify, I think the key bind will trigger the "Hey ..." flow (i.e., one press will make the assistant start listening for a command), rather than be a "listen while pressed".

**Comment by vojin7** [comment]
Sorry for the delay, wanted to update from 1.5.2 to 1.5.4, to make sure some issues I had are not due to obsolesence. 

One (unspoken) reason I thought a key press/bind would be helpful, is that I'm getting inconsitent behaviour from the  trigger phrase. Once it triggers, next time it doesn't, never went passed my first question-answer itteration. 

Trying it on a Mac, haven't yet tested it on my Windows machine, which is why I hadn't reported it (yet). 

So, if I understand correctly, every interaction with ChatGPT requires a trigger phrase, a la Google Home? it's not continuous?

This is why I thought that a keypress that would iniate a "listen" event each time and send it, would be more robust and avoid any ambiguity, in case voice triggering fails. An issue with voice assistants from the dawn of man... :) 

Of course, both could & should coexist.

`Just to clarify, I think the key bind will trigger the "Hey ..." flow (i.e., one press will make the assistant start listening for a command), rather than be a "listen while pressed".`

To finally answer you question: yep, the former - that would work great and would be much easie for you to implement, I belive. 👍

**Comment by idosal** [comment]
It is like Google Home. I'm getting reasonably consistent behavior from "Hey girl" if there isn't a lot of noise. You can customize it in the options tab to something more straightforward like "Hi". Note that there are 2 options to prompt -
- Say the trigger, wait for the beep and red icon, and then state your command.
- Say the trigger and immediately state your command.
In any case, I'll see what I can do about triggering it from the key bind. :)

**Comment by vojin7** [comment]
Awesome. It could be the case I was mumbling a bit. It's the middle of the night in my locale and it would be super strange me yelling "Hey girl" while family members are sound asleep, lol. Someone might get ideas. :)

Thanks again, keep it up!

**Comment by idosal** [comment]
Available in 1.6.0 from Releases. Version 1.4.2 was introduced to the Chrome Web Store, so I'll submit the updated version.

**Comment by neoOpus** [comment]
Ctrl+Shift+E in edge trigger search, so it would be better to have a different one or to be able to change it ourselves...
